### ISSUE TITLE
Parsing of the calendar failed

### ISSUE THREAD

**Issue by RealFriesi** [jazzband/icalevents#21]
```Python
Traceback (most recent call last):
  File "C:/Userdir/PycharmProjects/EPDUI/main.py", line 18, in <module>
    frame.eventlist(0, 3, 0, 10, 5, "https://calendar.google.com/calendar/ical/**********/basic.ics")
  File "C:\Userdir\PycharmProjects\EPDUI\epdui\epdui.py", line 85, in eventlist
    ev = events(ical_url)
  File "C:\Userdir\Anaconda3\envs\EPDUI\lib\site-packages\icalevents\icalevents.py", line 30, in events
    found_events += parse_events(content)
  File "C:\Userdir\Anaconda3\envs\EPDUI\lib\site-packages\icalevents\icalparser.py", line 247, in parse_events
    e = create_event(component)
  File "C:\Userdir\Anaconda3\envs\EPDUI\lib\site-packages\icalevents\icalparser.py", line 159, in create_event
    event.summary = str(component.get('summary'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 28: ordinal not in range(128)

```

![bitmoji](https://render.bitstrips.com/v2/cpanel/dd22deef-9d74-45af-b8bb-1b225e029a51-24a93aac-2341-4324-9129-32e68b698d30-v1.png?transparent=1&palette=1&width=246)

**Comment by PabloCastellano** [comment]
@Friesinator did you try using Python 3?

**Comment by Friesinator** [comment]
yep python 3.6

**Comment by eigenmannmartin** [comment]
I believe this is fixes - reopen if that is not the case :-)
